
source = $HOME/.config/hypr/colors.conf

$fn_greet=echo "vic"

$font4 = Musashi Brush
$font2 = Musashi Brush
$font3 = Musashi Brush

general {
    hide_cursor = true
    ignore_empty_input = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = $HOME/.wa.jpg
    blur_radius = 3
    blur_passes = 2
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.25) # no fill

    outer_color = $outline
    check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = $on_primary_container
    fade_on_empty = false
    rounding = 40

    font_family = $font2
    placeholder_text = <span size="28000">Input password</span>
    fail_text = $PAMFAIL

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = ✧
    # dots_size = 0.4
    dots_spacing = 0.4

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, -400
    halign = center
    valign = center
}

shape {
	size = 20%, 5%
	position = 0, -300
	halign = center
	valign = center
	color = rgba(0, 0, 0, 0.25)
	rounding = 40
	border_size = 3
	border_color = $outline
	}


label {
	text = cmd[update:60000] $fn_greet
	color = $on_primary_container
	font_family = $font2
	font_size = 45
	position = 0, -300
	halign = center
	valign = center
	}

# TIME HR
label {
    monitor =
    text = cmd[update:30000] date +"%I" # update every 30 seconds
    font_size = 360 # previously 240

    font_family = $font3
    color = $primary

    position = -290, 300
    halign = center
    valign = center
}

# TIME Min
label {
    monitor =
    text = cmd[update:30000] date +"%M" # update every 30 seconds
    font_size = 360 # previously 240
    font_family = $font3
    color = $primary

    position = 290, 300
    halign = center
    valign = center
}

shape {
	size = 0%, 10%
	position = 0, -350
	halign = center
	valign = top
	border_size = 2
	border_color = $primary
	rounding = 40
}

image {
	monitor = 
	path = ~/.face
	size = 250
	rounding = -1
	position = 0, -75
	halign = center
	valign = center
	border_size = 2
	border_color = $outline
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%d %B %Y" # update every 60 seconds
    font_size = 75 #40 previously
    font_family = $font4
    color = $primary

    position = -50, 30
    halign = right
    valign = bottom
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A" # update every 60 seconds
    font_size = 75 #40 previously
    font_family = $font2
    color = $primary

    position = 50, 30
    halign = left
    valign = bottom
}

